version: '3.8'

services:
  backend:
    build:
      context: ../..  # root project directory
      dockerfile: infra/docker/FSF.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=football_stats;Username=postgres;Password=password
    depends_on:
      - db

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: football_stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: